In [ ]:

import pandas as pd

In [ ]:
df = pd.read_csv("popular_people.csv")
df

,name,gender,known_for_department,original_name,popularity
0,Eric Larson,2,Visual Effects,Eric Larson,47.9780
1,Robert Middlemass,2,Acting,Robert Middlemass,47.8017
2,María Vaner,1,Acting,María Vaner,47.2016
3,Carl Wharton,2,Acting,Carl Wharton,36.3365
4,Victor Moore,2,Acting,Victor Moore,35.9181
...,...,...,...,...,...
9975,Tamu Blackwell,1,Acting,Tamu Blackwell,1.0432
9976,Yoshio Urasawa,2,Writing,浦沢義雄,1.1777
9977,Miko Hughes,2,Acting,Miko Hughes,1.5346
9978,Phoebe Fox,1,Acting,Phoebe Fox,1.1656
9979,Debora Calì,1,Acting,Debora Calì,1.2658

In [ ]:
df.head()

,name,gender,known_for_department,original_name,popularity
0,Eric Larson,2,Visual Effects,Eric Larson,47.9780
1,Robert Middlemass,2,Acting,Robert Middlemass,47.8017
2,María Vaner,1,Acting,María Vaner,47.2016
3,Carl Wharton,2,Acting,Carl Wharton,36.3365
4,Victor Moore,2,Acting,Victor Moore,35.9181

In [ ]:
df = df.drop(columns=[''])
df

In [ ]:
#df.info()

In [ ]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  9980 non-null   str
 1   gender                9980 non-null   int32
 2   known_for_department  9975 non-null   category
 3   original_name         9980 non-null   str
 4   popularity            9980 non-null   float64
dtypes: category(1), float64(1), int32(1), str(2)
memory usage: 1.4 MB

In [ ]:
df.memory_usage(deep=True)

Index                      132
name                    626478
gender                   79840
known_for_department     10092
original_name           674641
popularity               79840
dtype: int64

In [ ]:
df['known_for_department'].unique()

<StringArray>
[   'Visual Effects',            'Acting',         'Directing',
           'Writing',           'Editing',        'Production',
          'Lighting',             'Sound',            'Camera',
              'Crew',               'Art',           'Creator',
 'Costume & Make-Up',                 nan]
Length: 14, dtype: str

int 
categoria
str -> muito espaço
float -> muito espaço
booleano -> pouco espaço

In [ ]:
print(df["known_for_department"].head(10))

0    Visual Effects
1            Acting
2            Acting
3            Acting
4            Acting
5            Acting
6            Acting
7            Acting
8            Acting
9            Acting
Name: known_for_department, dtype: str

In [ ]:
df['known_for_department'] = df['known_for_department'].map({'Visual Effects': 0,'Acting': 1,'Directing':2,'Writing':3,'Editing':4,'Production':5,'Lighting':6,'Sound':7,'Camera':8,'Crew':9, 'Art':10, 'Creator':11, 'Costume & Make-Up':12}).astype('category')
df

,name,gender,known_for_department,original_name,popularity
0,Eric Larson,2,0.0,Eric Larson,47.9780
1,Robert Middlemass,2,1.0,Robert Middlemass,47.8017
2,María Vaner,1,1.0,María Vaner,47.2016
3,Carl Wharton,2,1.0,Carl Wharton,36.3365
4,Victor Moore,2,1.0,Victor Moore,35.9181
...,...,...,...,...,...
9975,Tamu Blackwell,1,1.0,Tamu Blackwell,1.0432
9976,Yoshio Urasawa,2,3.0,浦沢義雄,1.1777
9977,Miko Hughes,2,1.0,Miko Hughes,1.5346
9978,Phoebe Fox,1,1.0,Phoebe Fox,1.1656
9979,Debora Calì,1,1.0,Debora Calì,1.2658

In [ ]:
#mapping = {
    #'Visual Effects': 1,
    #'Acting': 2,
    #'Directing': 3,
    #'Writing': 4,
    #'Editing': 5,
    #'Production': 6,
    #'Lighting': 7,
    #'Sound': 8,
    #'Camera': 9,
    #'Crew': 10,
    #'Art': 11,
    #'Creator': 12,
    #'Costume & Make-Up': 13
#}

#df['known_for_department'] = df['known_for_department'].map(mapping).fillna(0).astype('category')

In [ ]:
df['gender'].unique()

array([2, 1, 0, 3])

In [ ]:
df['gender'] = df['gender'].astype('int32')
df

,name,gender,known_for_department,original_name,popularity
0,Eric Larson,2,Visual Effects,Eric Larson,47.9780
1,Robert Middlemass,2,Acting,Robert Middlemass,47.8017
2,María Vaner,1,Acting,María Vaner,47.2016
3,Carl Wharton,2,Acting,Carl Wharton,36.3365
4,Victor Moore,2,Acting,Victor Moore,35.9181
...,...,...,...,...,...
9975,Tamu Blackwell,1,Acting,Tamu Blackwell,1.0432
9976,Yoshio Urasawa,2,Writing,浦沢義雄,1.1777
9977,Miko Hughes,2,Acting,Miko Hughes,1.5346
9978,Phoebe Fox,1,Acting,Phoebe Fox,1.1656
9979,Debora Calì,1,Acting,Debora Calì,1.2658

In [ ]:
df.describe