In [4]:

import pandas as pd

In [5]:
df = pd.read_csv("crime_rate_safety_analysis.csv")
df

,incident_id,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,CRM0000001,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,...,2,46,No,No,No,No Coverage,Poorly Lit,3,62.8,No
1,CRM0000002,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,...,2,115,No,Yes,No,Partial Coverage,Partially Lit,1,50.7,No
2,CRM0000003,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,...,1,56,Yes,No,No,No Coverage,Well Lit,0,61.3,Yes
3,CRM0000004,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,...,4,44,Yes,Yes,No,Partial Coverage,Partially Lit,6,51.7,Yes
4,CRM0000005,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,...,5,111,No,Unknown,Yes,Partial Coverage,Partially Lit,2,52.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CRM0009996,2024,11,Thursday,Winter,Morning (6am-12pm),Turkey,Suburban,327,Burglary,...,3,27,No,Yes,No,Partial Coverage,Well Lit,5,75.6,No
9996,CRM0009997,2024,4,Tuesday,Spring,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,...,5,41,No,No,No,Partial Coverage,Partially Lit,0,61.4,No
9997,CRM0009998,2024,11,Tuesday,Summer,Evening (6pm-10pm),France,Suburban,436,Assault,...,3,30,Unknown,No,Yes,Partial Coverage,Poorly Lit,1,65.1,Yes
9998,CRM0009999,2022,1,Friday,Summer,Evening (6pm-10pm),USA,Rural,169,Cybercrime,...,1,27,Unknown,No,No,Partial Coverage,Well Lit,2,77.5,No
9999,CRM0010000,2021,2,Thursday,Summer,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,...,5,123,No,No,Unknown,Partial Coverage,Well Lit,1,51.4,No

In [17]:
df.head()

,incident_id,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,CRM0000001,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,...,2,46,No,No,No,No Coverage,Poorly Lit,3,62.8,No
1,CRM0000002,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,...,2,115,No,Yes,No,Partial Coverage,Partially Lit,1,50.7,No
2,CRM0000003,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,...,1,56,Yes,No,No,No Coverage,Well Lit,0,61.3,Yes
3,CRM0000004,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,...,4,44,Yes,Yes,No,Partial Coverage,Partially Lit,6,51.7,Yes
4,CRM0000005,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,...,5,111,No,Unknown,Yes,Partial Coverage,Partially Lit,2,52.0,No

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   incident_id                    10000 non-null  str
 1   year                           10000 non-null  int64
 2   month                          10000 non-null  int64
 3   day_of_week                    10000 non-null  str
 4   season                         10000 non-null  str
 5   time_of_day                    10000 non-null  str
 6   country                        10000 non-null  str
 7   area_type                      10000 non-null  str
 8   population_density_per_sqkm    10000 non-null  int64
 9   crime_type                     10000 non-null  str
 10  crime_severity_score           10000 non-null  float64
 11  victim_count                   10000 non-null  int64
 12  victim_gender                  10000 non-null  str
 13  victim_age_group               10000 non-null  str
 14  injuries_reported              10000 non-null  int64
 15  fatalities                     10000 non-null  int64
 16  financial_loss_usd             10000 non-null  float64
 17  weapon_used                    6428 non-null   str
 18  suspect_status                 10000 non-null  str
 19  case_status                    10000 non-null  str
 20  reporting_method               10000 non-null  str
 21  response_time_minutes          10000 non-null  float64
 22  officers_assigned              10000 non-null  int64
 23  investigation_duration_days    10000 non-null  int64
 24  repeat_offender                10000 non-null  str
 25  gang_related                   10000 non-null  str
 26  drug_related                   10000 non-null  str
 27  cctv_coverage                  10000 non-null  str
 28  lighting_condition             10000 non-null  str
 29  prior_incidents_same_location  10000 non-null  int64
 30  safety_index                   10000 non-null  float64
 31  crime_resolved                 10000 non-null  str
dtypes: float64(4), int64(9), str(19)
memory usage: 2.4 MB

In [21]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   year                           10000 non-null  int64
 1   month                          10000 non-null  int64
 2   day_of_week                    10000 non-null  str
 3   season                         10000 non-null  category
 4   time_of_day                    10000 non-null  str
 5   country                        10000 non-null  str
 6   area_type                      10000 non-null  category
 7   population_density_per_sqkm    10000 non-null  int64
 8   crime_type                     10000 non-null  str
 9   crime_severity_score           10000 non-null  float64
 10  victim_count                   10000 non-null  int64
 11  victim_gender                  10000 non-null  category
 12  victim_age_group               10000 non-null  int64
 13  injuries_reported              10000 non-null  int64
 14  fatalities                     10000 non-null  int64
 15  financial_loss_usd             10000 non-null  float64
 16  weapon_used                    6428 non-null   str
 17  suspect_status                 10000 non-null  str
 18  case_status                    10000 non-null  str
 19  reporting_method               10000 non-null  str
 20  response_time_minutes          10000 non-null  float64
 21  officers_assigned              10000 non-null  int64
 22  investigation_duration_days    10000 non-null  int64
 23  repeat_offender                10000 non-null  str
 24  gang_related                   10000 non-null  str
 25  drug_related                   10000 non-null  str
 26  cctv_coverage                  10000 non-null  str
 27  lighting_condition             10000 non-null  int64
 28  prior_incidents_same_location  10000 non-null  int64
 29  safety_index                   10000 non-null  float64
 30  crime_resolved                 10000 non-null  bool
dtypes: bool(1), category(3), float64(4), int64(11), str(12)
memory usage: 7.7 MB

In [103]:
df.memory_usage(deep=True)

Index                               132
incident_id                      590000
year                              80000
month                             80000
day_of_week                      561536
season                           550000
time_of_day                      671172
country                          552601
area_type                        549734
population_density_per_sqkm       80000
crime_type                       573263
crime_severity_score              80000
victim_count                      80000
victim_gender                    540131
victim_age_group                 540632
injuries_reported                 80000
fatalities                        80000
financial_loss_usd                80000
weapon_used                      475685
suspect_status                   590662
case_status                      638574
reporting_method                 629984
response_time_minutes             80000
officers_assigned                 80000
investigation_duration_days       80000
repeat_offender                  519697
gang_related                     517665
drug_related                     518877
cctv_coverage                    628285
lighting_condition               593035
prior_incidents_same_location     80000
safety_index                      80000
crime_resolved                   512957
dtype: int64

In [66]:
df.columns

Index(['incident_id', 'year', 'month', 'day_of_week', 'season', 'time_of_day',
       'country', 'area_type', 'population_density_per_sqkm', 'crime_type',
       'crime_severity_score', 'victim_count', 'victim_gender',
       'victim_age_group', 'injuries_reported', 'fatalities',
       'financial_loss_usd', 'weapon_used', 'suspect_status', 'case_status',
       'reporting_method', 'response_time_minutes', 'officers_assigned',
       'investigation_duration_days', 'repeat_offender', 'gang_related',
       'drug_related', 'cctv_coverage', 'lighting_condition',
       'prior_incidents_same_location', 'safety_index', 'crime_resolved'],
      dtype='str')

In [7]:
df = df.drop(columns=['incident_id'])
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,Poorly Lit,3,62.8,No
1,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,Partially Lit,1,50.7,No
2,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,Well Lit,0,61.3,Yes
3,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,Partially Lit,6,51.7,Yes
4,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,Partially Lit,2,52.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,Winter,Morning (6am-12pm),Turkey,Suburban,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,Well Lit,5,75.6,No
9996,2024,4,Tuesday,Spring,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,Partially Lit,0,61.4,No
9997,2024,11,Tuesday,Summer,Evening (6pm-10pm),France,Suburban,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,Poorly Lit,1,65.1,Yes
9998,2022,1,Friday,Summer,Evening (6pm-10pm),USA,Rural,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,Well Lit,2,77.5,No
9999,2021,2,Thursday,Summer,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,Well Lit,1,51.4,No

-int 
-categoria
-str -> muito espaço
-float -> muito espaço
-booleano -> pouco espaço

In [8]:
df['lighting_condition'].unique()

<StringArray>
['Poorly Lit', 'Partially Lit', 'Well Lit', 'No Lighting']
Length: 4, dtype: str

In [9]:
df['lighting_condition'] = df['lighting_condition'].map({'Poorly Lit': 0, 'Partially Lit': 1, 'Well Lit': 2, 'No Lighting': 3})
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,0,3,62.8,No
1,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,1,1,50.7,No
2,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,2,0,61.3,Yes
3,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,1,6,51.7,Yes
4,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,1,2,52.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,Winter,Morning (6am-12pm),Turkey,Suburban,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,2,5,75.6,No
9996,2024,4,Tuesday,Spring,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,1,0,61.4,No
9997,2024,11,Tuesday,Summer,Evening (6pm-10pm),France,Suburban,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,0,1,65.1,Yes
9998,2022,1,Friday,Summer,Evening (6pm-10pm),USA,Rural,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,2,2,77.5,No
9999,2021,2,Thursday,Summer,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,2,1,51.4,No

In [10]:
df['crime_resolved'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [11]:
df['crime_resolved'] = df['crime_resolved'].map({'No': 0, 'Yes': 1}).astype(bool)
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,0,3,62.8,False
1,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,1,1,50.7,False
2,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,2,0,61.3,True
3,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,1,6,51.7,True
4,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,1,2,52.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,Winter,Morning (6am-12pm),Turkey,Suburban,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,2,5,75.6,False
9996,2024,4,Tuesday,Spring,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,1,0,61.4,False
9997,2024,11,Tuesday,Summer,Evening (6pm-10pm),France,Suburban,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,0,1,65.1,True
9998,2022,1,Friday,Summer,Evening (6pm-10pm),USA,Rural,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,2,2,77.5,False
9999,2021,2,Thursday,Summer,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,2,1,51.4,False

In [12]:
df['season'].unique()

<StringArray>
['Winter', 'Autumn', 'Spring', 'Summer']
Length: 4, dtype: str

In [13]:
df['season'] = df['season'].map({'Winter': 0, 'Autumn': 1, 'Spring': 2, 'Summer': 3}).astype('category')
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,0,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,0,3,62.8,False
1,2024,4,Sunday,1,Night (10pm-2am),Pakistan,Rural,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,1,1,50.7,False
2,2023,2,Tuesday,2,Afternoon (12pm-6pm),USA,Rural,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,2,0,61.3,True
3,2023,5,Saturday,1,Evening (6pm-10pm),India,Rural,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,1,6,51.7,True
4,2021,11,Saturday,2,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,1,2,52.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,0,Morning (6am-12pm),Turkey,Suburban,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,2,5,75.6,False
9996,2024,4,Tuesday,2,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,1,0,61.4,False
9997,2024,11,Tuesday,3,Evening (6pm-10pm),France,Suburban,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,0,1,65.1,True
9998,2022,1,Friday,3,Evening (6pm-10pm),USA,Rural,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,2,2,77.5,False
9999,2021,2,Thursday,3,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,2,1,51.4,False

In [14]:
df['area_type'].unique()

<StringArray>
['Remote', 'Rural', 'Urban', 'Suburban']
Length: 4, dtype: str

In [164]:
#print(df[" "].head(10))

In [15]:
df['area_type'] = df['area_type'].map({'Remote': 0,'Rural': 1,'Urban':2,'Suburban':3}).astype('category')
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,0,Afternoon (12pm-6pm),Germany,0,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,0,3,62.8,False
1,2024,4,Sunday,1,Night (10pm-2am),Pakistan,1,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,1,1,50.7,False
2,2023,2,Tuesday,2,Afternoon (12pm-6pm),USA,1,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,2,0,61.3,True
3,2023,5,Saturday,1,Evening (6pm-10pm),India,1,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,1,6,51.7,True
4,2021,11,Saturday,2,Afternoon (12pm-6pm),Mexico,2,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,1,2,52.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,0,Morning (6am-12pm),Turkey,3,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,2,5,75.6,False
9996,2024,4,Tuesday,2,Afternoon (12pm-6pm),Germany,2,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,1,0,61.4,False
9997,2024,11,Tuesday,3,Evening (6pm-10pm),France,3,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,0,1,65.1,True
9998,2022,1,Friday,3,Evening (6pm-10pm),USA,1,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,2,2,77.5,False
9999,2021,2,Thursday,3,Night (10pm-2am),Pakistan,3,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,2,1,51.4,False

In [16]:
df['victim_gender'].unique()

<StringArray>
['Female', 'Male', 'Unknown']
Length: 3, dtype: str

In [17]:
df['victim_gender'] = df['victim_gender'].map({'Female': 0,'Male': 1,'Unknown':2}).astype('category')
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,0,Afternoon (12pm-6pm),Germany,0,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,0,3,62.8,False
1,2024,4,Sunday,1,Night (10pm-2am),Pakistan,1,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,1,1,50.7,False
2,2023,2,Tuesday,2,Afternoon (12pm-6pm),USA,1,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,2,0,61.3,True
3,2023,5,Saturday,1,Evening (6pm-10pm),India,1,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,1,6,51.7,True
4,2021,11,Saturday,2,Afternoon (12pm-6pm),Mexico,2,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,1,2,52.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,0,Morning (6am-12pm),Turkey,3,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,2,5,75.6,False
9996,2024,4,Tuesday,2,Afternoon (12pm-6pm),Germany,2,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,1,0,61.4,False
9997,2024,11,Tuesday,3,Evening (6pm-10pm),France,3,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,0,1,65.1,True
9998,2022,1,Friday,3,Evening (6pm-10pm),USA,1,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,2,2,77.5,False
9999,2021,2,Thursday,3,Night (10pm-2am),Pakistan,3,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,2,1,51.4,False

In [153]:
df.describe

<bound method NDFrame.describe of       year  month day_of_week season           time_of_day   country  \
0     2022      7   Wednesday    NaN  Afternoon (12pm-6pm)   Germany
1     2024      4      Sunday    NaN      Night (10pm-2am)  Pakistan
2     2023      2     Tuesday    NaN  Afternoon (12pm-6pm)       USA
3     2023      5    Saturday    NaN    Evening (6pm-10pm)     India
4     2021     11    Saturday    NaN  Afternoon (12pm-6pm)    Mexico
...    ...    ...         ...    ...                   ...       ...
9995  2024     11    Thursday    NaN    Morning (6am-12pm)    Turkey
9996  2024      4     Tuesday    NaN  Afternoon (12pm-6pm)   Germany
9997  2024     11     Tuesday    NaN    Evening (6pm-10pm)    France
9998  2022      1      Friday    NaN    Evening (6pm-10pm)       USA
9999  2021      2    Thursday    NaN      Night (10pm-2am)  Pakistan

     area_type  population_density_per_sqkm  crime_type  crime_severity_score  \
0          NaN                           16   Vandalism                   2.7
1          NaN                          252       Fraud                   3.5
2          NaN                          136     Assault                   5.7
3          NaN                          354     Robbery                   7.0
4          NaN                          817    Burglary                   4.6
...        ...                          ...         ...                   ...
9995       NaN                          327    Burglary                   5.2
9996       NaN                         1136    Burglary                   7.0
9997       NaN                          436     Assault                   5.2
9998       NaN                          169  Cybercrime                   5.4
9999       NaN                          332   Vandalism                   2.3

      ...  officers_assigned investigation_duration_days repeat_offender  \
0     ...                  2                          46              No
1     ...                  2                         115              No
2     ...                  1                          56             Yes
3     ...                  4                          44             Yes
4     ...                  5                         111              No
...   ...                ...                         ...             ...
9995  ...                  3                          27              No
9996  ...                  5                          41              No
9997  ...                  3                          30         Unknown
9998  ...                  1                          27         Unknown
9999  ...                  5                         123              No

      gang_related  drug_related     cctv_coverage lighting_condition  \
0               No            No       No Coverage                  0
1              Yes            No  Partial Coverage                  1
2               No            No       No Coverage                  2
3              Yes            No  Partial Coverage                  1
4          Unknown           Yes  Partial Coverage                  1
...            ...           ...               ...                ...
9995           Yes            No  Partial Coverage                  2
9996            No            No  Partial Coverage                  1
9997            No           Yes  Partial Coverage                  0
9998            No            No  Partial Coverage                  2
9999            No       Unknown  Partial Coverage                  2

     prior_incidents_same_location safety_index crime_resolved
0                                3         62.8           True
1                                1         50.7           True
2                                0         61.3           True
3                                6         51.7           True
4                                2         52.0           True
...                            ...          ...            ...
9995                             5         75.6           True
9996                             0         61.4           True
9997                             1         65.1           True
9998                             2         77.5           True
9999                             1         51.4           True

[10000 rows x 31 columns]>

In [19]:
df['victim_age_group'].unique()

<StringArray>
['65+', '26-35', '18-25', '36-45', '46-55', '56-65', 'Under 18']
Length: 7, dtype: str

In [20]:
df['victim_age_group'] = df['victim_age_group'].map({'65+': 6, '26-35': 2, '18-25': 1, '36-45': 3, '46-55': 4, '56-65': 5, 'Under 18': 0})
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,0,Afternoon (12pm-6pm),Germany,0,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,0,3,62.8,False
1,2024,4,Sunday,1,Night (10pm-2am),Pakistan,1,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,1,1,50.7,False
2,2023,2,Tuesday,2,Afternoon (12pm-6pm),USA,1,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,2,0,61.3,True
3,2023,5,Saturday,1,Evening (6pm-10pm),India,1,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,1,6,51.7,True
4,2021,11,Saturday,2,Afternoon (12pm-6pm),Mexico,2,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,1,2,52.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,0,Morning (6am-12pm),Turkey,3,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,2,5,75.6,False
9996,2024,4,Tuesday,2,Afternoon (12pm-6pm),Germany,2,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,1,0,61.4,False
9997,2024,11,Tuesday,3,Evening (6pm-10pm),France,3,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,0,1,65.1,True
9998,2022,1,Friday,3,Evening (6pm-10pm),USA,1,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,2,2,77.5,False
9999,2021,2,Thursday,3,Night (10pm-2am),Pakistan,3,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,2,1,51.4,False